import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="w-screen h-screen bg-gradient-to-br from-orange-100 dark:from-orange-700 dark:to-orange-950 text-black/95 dark:text-white/95">
        {children}
      </body>
    </html>
  );
}
